# Generated by Django 5.2.7 on 2026-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship_placement',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('internship_placement', models.CharField(max_length=100)),
                ('week_number', models.IntegerField()),
                ('activites', models.TextField()),
                ('log_date', models.DateField()),
            ],
        ),
    ]
